# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dec0a0c1f1bee60b0a67e728cf871af7e55fd899e483a474733b2a6254998d99858294be4795ce24ee1c8cba53b0fb8e1ef13f9fe9f1be0833e8f05c58a7d514

test:
  secret_key_base: b3afae2649782d230eb16f9fb38aa693f4f0887e5c040239a60c390edcee3a5f2771abb79496b2ec99b475f8b9c702c72133372744cfb908efcaa019ef079e08

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
